on:
  release:
    types:
      - published
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-
      
      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-${{ github.sha }}
          include-hidden-files: true
          path: |
            ~/AppData/Local/.xmake

  upload-to-release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Mod
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-${{ github.sha }}
          path: artifact

      - name: Archive release
        run: |
          zip -r ../${{ github.event.repository.name }}-windows.zip *
        working-directory: artifact

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.event.repository.name }}-windows.zip